channels:

  - bioconda
  - conda-forge
  - defaults

dependencies:

  # Base Python/R installations
  - r=3.5

  # Packages needed for compiling the `knitr-PDR` report
  - r-knitr=1.23
  - r-tinytex=0.8  
