# Paths
datadir: "data/test-data/fastq/"
analysisdir: "results/"

# Indexes and reference files
REF: "data/idx/genome.fa"
STAR_REF: "data/idx/STARIndex/"
REF_GENE: "data/idx/genes.bed"
REF_GTF: "data/idx/genes.gtf"

# Software parameters
STAR_THREADS: 2
