# Data path
datadir: "data/test-data/fastq/"

# Software paths
fastqcdir: "results/fastqc/"
sortmernadir: "results/sortmerna/"
aligndir: "results/star/"
rseqcdir: "results/rseqc/"
countdir: "results/counts/"
multiqcdir: "results/multiqc/"

# Indexes and reference files
REF: "data/idx/genome.fa"
STAR_REF: "data/idx/STARIndex/"
REF_GENE: "data/idx/genes.bed"
REF_GTF: "data/idx/genes.gtf"

# Software parameters
STAR_THREADS: 2
