# Paths
datadir: "data/test-data/fastq/"
resultsdir: "results/"

# Indexes and reference files
ASSEMBLY: "Homo_sapiens.GRCh38.97"
STAR_REF: "data/idx/STARIndex/"
REF_GENE: "data/idx/genes.bed"

# Software parameters
STAR_THREADS: 2
