# Data path
datadir: "data/test-data/fastq/"

# Software paths
fastqcdir: "results/fastqc/"
aligndir: "results/star/"
rseqcdir: "results/rseqc/"
multiqcdir: "results/multiqc/"

# Indexes and reference files
REF: "data/idx/genome.fa"
STAR_REF: "data/idx/STARIndex/"
REF_GENE: "data/idx/genes.bed"

# Software parameters
STAR_THREADS: 2
