import glob

# Config
configfile: "config.yml"
datadir = config["datadir"]
resultsdir = config["resultsdir"]

# Relative paths
fastqcdir = resultsdir + "fastqc/"
sortmernadir = resultsdir + "sortmerna/"
aligndir = resultsdir + "star/"
rseqcdir = resultsdir + "rseqc/"
countdir = resultsdir + "counts/"
multiqcdir = resultsdir + "multiqc/"

# Get all first-pair FASTQ files in the fastq data directory
fastq_files = glob.glob(datadir + "*.fastq.gz")
fastq_files = [s.replace('.fastq.gz', '') for s in fastq_files]
fastq_files = [s.replace(datadir, '') for s in fastq_files]

# Get sample names
samples = [s.replace('_1', '') for s in fastq_files]
samples = [s.replace('_2', '') for s in samples]
fastq_samples = samples
samples = list(set(samples))

# Include external rules
include: "rules/FastQC.smk"
include: "rules/featureCounts.smk"
include: "rules/MultiQC.smk"
include: "rules/RSeqC.smk"
include: "rules/SortMeRNA.smk"
include: "rules/STAR-PE.smk"

# Rule: final outputs
rule all:
    input:
        resultsdir + "multiqc-report.html",
        resultsdir + "collected-counts.txt"
