import glob

# Config file
configfile: "config.yml"

# Paths
datadir = config["datadir"]
analysisdir = config["analysisdir"]
fastqcdir = analysisdir + "fastqc/"
sortmernadir = analysisdir + "sortmerna/"
aligndir = analysisdir + "star/"
rseqcdir = analysisdir + "rseqc/"
countdir = analysisdir + "counts/"
multiqcdir = analysisdir + "multiqc/"

# Get all first-pair FASTQ files in the fastq data directory
fastq_files = glob.glob(datadir + "*.fastq.gz")
fastq_files = [s.replace('.fastq.gz', '') for s in fastq_files]
fastq_files = [s.replace(datadir, '') for s in fastq_files]

# Get sample names
samples = [s.replace('_1', '') for s in fastq_files]
samples = [s.replace('_2', '') for s in samples]
fastq_samples = samples
samples = list(set(samples))

# Include external rules
include: "rules/FastQC.smk"
include: "rules/featureCounts.smk"
include: "rules/MultiQC.smk"
include: "rules/RSeqC.smk"
include: "rules/SortMeRNA.smk"
include: "rules/STAR-PE.smk"

# Rule: final output and cleanup
rule all:
    input:
        multiqcdir + "multiqc_report.html",
        countdir + "collected-counts.txt"
